from turtle import *

setup(500, 500)
speed(10)
bgcolor("black")
shape("turtle")
def drawcircle(size):
 pendown()
 setheading(180)
 begin_fill()
 circle(size,360)
 end_fill()

def drawrectangle(length,width):
   pendown()
   begin_fill()
   forward(length)
   right(90)
   forward(width)
   right(90)
   forward(length)
   right(90)
   forward(width)
   right(90)
   end_fill()
   
def head():
    color("blue","blue")
    penup()
    goto(0,100)
    drawcircle(75)  
    color("white","white")
    penup()
    goto(0,72)
    drawcircle(60)
def eyes():
   color("black","white")
   penup()
   goto(-15,80)
   drawcircle(17)
   color("black","white")
   penup()
   goto(19,80)
   drawcircle(17)
   color("black","black")
   penup()
   goto(-8,70)
   drawcircle(6)
   color("white","white")
   penup()
   goto(-8,66)
   drawcircle(2)
   color("black","black")
   penup()
   goto(12,70)
   drawcircle(6)
   color("white","white")
   penup()
   goto(12,66)
   drawcircle(2)
def nose():
   penup()
   color("red","red")
   goto(0,40)
   pendown()
   drawcircle(7)
def mouth():
   penup()
   color("black","black")
   goto(-30,-20)
   pendown()
   setheading(-27)
   circle(70,55)
   penup()
   goto(0,26)
   pendown()
   goto(0,-26)   
def whiskers():
    color("black", "black")
    penup()
    goto(10, 5)
    pendown()
    goto(-40, 5)
    penup()
    goto(10, 5)
    pendown()
    goto(40, 5)
    penup()
    goto(-10, 15)
    pendown()
    goto(-40, 20)
    penup()
    goto(10, 15)
    pendown()
    goto(40, 20)
    penup()
    goto(-10, -5)
    pendown()
    goto(-40, -10)
    penup()
    goto(10, -5)
    pendown()
    goto(40, -10)
def body():
   color("blue","blue")
   penup()
   goto(0,-35)
   drawcircle(50)
   color("white","white")
   penup()
   goto(0,-35)
   drawcircle(40)
   penup()
   color("red","red")
   goto(35,-50)
   drawrectangle(80,10)
   color("white","white")
   penup()
   goto(15,-127)
   pendown()
   setheading(90)
   begin_fill()
   circle(14,180)
   end_fill()
def feet():
   color("black", "white")
   penup()
   goto(-30,-110)
   drawcircle(20)
   color("black", "white")
   penup()
   goto(30,-110)
   drawcircle(20)
def arms():
   color("blue", "blue")
   penup()
   begin_fill()
   goto(-51,-50)
   pendown()
   goto (-51,-75)
   left(70)
   goto(-76,-85)
   left(70)
   goto(-86,-70)
   left(70)
   goto(-51,-50)
   end_fill()
   penup()
   goto(49, -50)
   color("blue", "blue")
   begin_fill()
   pendown()
   goto(49, -75)
   left(70)
   goto(74, -85)
   left(70)
   goto(84, -70)
   left(70)
   goto(49, -50)
   end_fill()
def hands():
   color("black","white")
   penup()
   goto(-90,-71)
   drawcircle(15)
   color("black","white")
   penup()
   goto(90,-71)
   drawcircle(15)   
head()
eyes()
nose()
mouth()   
whiskers() 
body()
feet()
arms()
hands()
done()